default:

vectorExample: vectorExample.cpp
	g++ -o vectorExample vectorExample.cpp
	chmod +x vectorExample

twoDimVector: twoDimVector.cpp
	g++ -o twoDimVector twoDimVector.cpp
	chmod +x twoDimVector
