default:

userDatabase: userDatabase.cpp
	g++ -o userDatabase userDatabase.cpp
	chmod +x userDatabase

vectorExample: vectorExample.cpp
	g++ -o vectorExample vectorExample.cpp
	chmod +x vectorExample

twoDimVector: twoDimVector.cpp
	g++ -o twoDimVector twoDimVector.cpp
	chmod +x twoDimVector
