default: ReadWriteBinData.cpp playerData.txt
	g++ ReadWriteBinData.cpp -o ReadWriteBinData
	chmod +x ReadWriteBinData

ReadFileTest: ReadFileTest.cpp playerData.txt
	g++ ReadFileTest.cpp -o ReadFileTest
	chmod +x ReadFileTest

WriteFileTest: WriteFileTest.cpp
	g++ WriteFileTest.cpp -o WriteFileTest
	chmod +x WriteFileTest
