default: enemy.cpp enemy.h enemyUsage.cpp
	g++ -std=c++0x -o enemyUsage enemy.cpp enemyUsage.cpp
	chmod +x ./enemyUsage

encounter: enemy.cpp enemy.h enemyEncounter.cpp
	g++ -std=c++0x -o enemyEncounter enemy.cpp enemyEncounter.cpp
	chmod +x ./enemyEncounter
