SimpleVirtualFunc: SimpleVirtualFunc.cpp
	g++ -std=c++11 -o SimpleVirtualFunc SimpleVirtualFunc.cpp
	chmod +x SimpleVirtualFunc

ObjectSlicing: ObjectSlicing.cpp
	g++ -std=c++11 -o ObjectSlicing ObjectSlicing.cpp
	chmod +x ObjectSlicing

ClassHierarchy: ClassHierarchy.cpp
	g++ -std=c++11 -o ClassHierarchy ClassHierarchy.cpp
	chmod +x ClassHierarchy
